name: exid_train
train: 0.9
abblation_val: 0.1
val: 0.1
test: 0.0
deploy: 0.0
image_width: 200
image_height: 80
dataset_dir: '../Datasets/Processed_exid/RenderedDataset/'
map_dirs :
  - '../Datasets/Processed_exid/Map/39-52.pickle'
  - '../Datasets/Processed_exid/Map/53-60.pickle'
  - '../Datasets/Processed_exid/Map/61-72.pickle'
  - '../Datasets/Processed_exid/Map/78-92.pickle'
dataset_ind: '[40,41,42,43,44,45,46,47,48,49,50,51,52,62,63,64,65,66,67,68,69,70,71,72,79,80,81,82,83,84,85,86,87,88,89,90,91,92,54,55,56,57,58,59,60]' # 83
map_ind : '[0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,1,1,1,1,1,1]' # 39 has been deleted

